#sdk: "/home/sreepal/.rvm/gems/ruby-1.8.7-head/gems/rhodes-3.3.1"
sdkversion: 3.3.0
name: weather_report
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.weatherreport
  BundleURLScheme: weatherreport
wp:
  productid: 'f7ddaef0-2962-012f-45ae-782bcb922bed'
symbian:
  uid: '0xe1e0b8b2'
android:
  version: 4.0

extensions: ["json", "rexml", "set", "another-extension"]
